CREATE USER IF NOT EXISTS 'JC'@'localhost:3306' IDENTIFIED BY 'YES';

DROP DATABASE IF EXISTS BOOK_PUBLISHER;
CREATE DATABASE BOOK_PUBLISHER;
USE BOOK_PUBLISHER;
GRANT ALL PRIVILEGES ON BOOK_PUBLISHER.* TO 'JC'@'localhost:3306';
FLUSH PRIVILEGES;

SET GLOBAL time_zone = '+5:00';